import os
import sys

def FrequentWords(Text, k):
    Patterns = {}
    FrequentPatterns = []
    for i in range (len(Text) - k + 1):
        Pattern = Text[i:k+i]
        if Pattern in Patterns:
            Patterns[Pattern] += 1
        else:
            Patterns[Pattern] = 1
    maxCount = max(Patterns.values())
    for i in Patterns:
        if Patterns[i] == maxCount:
            FrequentPatterns.append(i)
    return ' '.join(FrequentPatterns)

def main():
    Text = "CCGCTATTGCGACGTACCAAACCAACCGACGTACGAGTTGTGGAGTTGTGGAGTTGTGGAGTTGTGTGTGAGCCCGAGTTGTGCAAACCAACTGTGAGCCCCAAACCAACTGTGAGCCCGAGTTGTGGAGTTGTGTGTGAGCCCTGTGAGCCCCGACGTACCAAACCAACCGACGTACCCGCTATTGGAGTTGTGCGACGTACCAAACCAACGAGTTGTGCGACGTACCGACGTACGAGTTGTGCCGCTATTGCAAACCAACCAAACCAACCGACGTACCGACGTACCAAACCAACGAGTTGTGTGTGAGCCCGAGTTGTGCGACGTACCAAACCAACTGTGAGCCCTGTGAGCCCCAAACCAACCGACGTACCGACGTACCGACGTACCAAACCAACCCGCTATTGGAGTTGTGCAAACCAACTGTGAGCCCGAGTTGTGGAGTTGTGGAGTTGTGCAAACCAACTGTGAGCCCCCGCTATTGCAAACCAACTGTGAGCCCGAGTTGTGTGTGAGCCCGAGTTGTGTGTGAGCCCGAGTTGTGGAGTTGTGCCGCTATTGCAAACCAACCCGCTATTGTGTGAGCCCCAAACCAACGAGTTGTGCAAACCAACTGTGAGCCCCAAACCAACCAAACCAACCAAACCAACCCGCTATTGTGTGAGCCCCGACGTACCGACGTACCGACGTACCAAACCAACCGACGTACCGACGTACTGTGAGCCCCGACGTACCAAACCAACCCGCTATTGTGTGAGCCCGAGTTGTGCAAACCAACCGACGTACCCGCTATTGCAAACCAACCCGCTATTGTGTGAGCCCCGACGTACCAAACCAACGAGTTGTGCCGCTATTG"
    k = 11
    Results = FrequentWords(Text, k)
    print(Results)
        
main() 