import os
import sys
import math

def ProfileMost(string, k, matrix):
    max = -1
    res = ""
    for i in range (len(string) - k + 1):
        substring = string[i:i+k]
        prob = 1
        for j in range(k):
            if substring[j] == 'A':
                prob *= matrix[0][j]
            elif substring[j] == 'C':
                prob *= matrix[1][j]
            elif substring[j] == 'G':
                prob *= matrix[2][j]
            else:
                prob *= matrix[3][j]
            if prob == 0:
                break
        if prob == 0:
                continue    
        if prob > max:
            res = substring
            max = prob
    return res
            
string = "TGAGATGAGAAACTGTAACATCGGAGCACTCCTCCTCCCTTCGATAGTCGCAACAGATTTTCATGGTTGTGAACATGACGTTTTCACCAGCAAGTTCACTGTCTGGTAATCACTCAAAGGTGGAGTTCGCCAGATGGCATAGGAAGATCGAGGTCGAGTTGCGCAAAGGTTGCGTCCATACGAATTTGCCGAATGATTTCCGATAATGGATGGAGCTGTAGGAGTGATAGGGAATGGTCTATTCCCACATGATGAGACCGCAGGCCCTGAGTATTGCTTGTAATTGGACTTACACAATAGGCTTGCAATGAATACAATCTCATCCAAGTTGTACGGTCCGACTCTTGATCTCAGCGGCACTTGGCGAACAATGTTTGAAGTTCTAGCGCGGACAGGTCTTTTGGCCAGCCTCAACTACCGATGGGTGGCAGGAGTATAATATTGTCTATGGCCACAGAGCATCGCGGCACTCTTTCAGTCCTTCTAGAGAGCCGCAGGTGGTGGCCCCCGTACCGGAACGCTAGCGCACTTCGAAGTGTAATTAGTCCTTTTACAACCAATTACAGCTGCGCTATCAGGTCTCCGGATGATTTGGTAAGCTGTGAGGCCTCAACGAGCCGGAACCATTCCAGGGATTGCAAAACGGGGCAAAAACGTTAGTATTCGGATCTCCCGAGAGATATAGCTTGGGTTTGCAAAAGAAATCATAACGGACGATGCAGTACATCTCTTCATCCACTCGGTACATCCTAGCGCCAACGGTCTGATAGGGTGTGAATCCCTGAGCGTTATTTTACGAGACTAGATGAGATTGAAGTAATCCGGAGCACGCCGCTCAAATGTTGGTAACCAGCCCTGGCGGCGTTTTCACGCGGGGAATATTGCAGGTGGGATGGCCCGCCCAACATTCGATCAAGTGTATAGGGGCCAGTTAGGCTGTCCGGCCGGACATGGCTCATCGGCCGGACTGTTTCGGTCTTAAGGGACGACCATTAGCATA"
k = 13
matrix = [
    [0.224, 0.224, 0.342, 0.289, 0.303, 0.25, 0.303, 0.276, 0.289, 0.224, 0.237, 0.197, 0.184],
    [0.276, 0.237, 0.171, 0.316, 0.211, 0.303, 0.25, 0.368, 0.158, 0.237, 0.25, 0.303, 0.368],
    [0.25, 0.171, 0.211, 0.224, 0.263, 0.224, 0.237, 0.171, 0.25, 0.25, 0.237, 0.263, 0.224],
    [0.25, 0.368, 0.276, 0.171, 0.224, 0.224, 0.211, 0.184, 0.303, 0.289, 0.276, 0.237, 0.224]
]


print(ProfileMost(string, k, matrix))
        